### PR TITLE
Added Github Workflows

### PR DESCRIPTION
**Pull request by sandygross**
This directory is necessary for having GitHub workflows active. Please approve!

### CODE REVIEW

**Comment by sivakornchong** [comment]
I do not think this is necessary and ready to be deployed. Because we do not have the code infrastructure ready, all the github actions will not work anyway.  That is why all the automated checks here all failed... 
This ci-cd file sets up should be for milestone 4.

**Comment by sandygross** [comment]
Hi Oak, in Milestone 1 it says: "This time when you are prompted as whether to include GitHub Actions, say yes! In particular, choose option 3 (build + deploy)." Tiff said failing is normal right now on the course website. Thus, we should add it!

**Comment by czwcandy** [comment]
We can put workflow here as I asked other groups. It's okay that it shows 'failed' for now

**Review by sivakornchong — APPROVED** [review]
ci-cd file to be updated in the future, for now on, there will be alert with the merging.

**Pull request merged**
