### PR TITLE
Added environment file

### PR DESCRIPTION
**Pull request by sandygross**
Please try it and let me know whether it works and is ready for merging

### CODE REVIEW

**Comment by carinaya** [comment]
That looks great! would you mind to also add numpy cuz I am not sure if we will use it

**Comment by sandygross** [comment]
Numpy will be automatically installed as part of the dependencies that we are installing, but I can also add it explicitly if you want. Let me update it

**Comment by carinaya** [comment]
> Numpy will be automatically installed as part of the dependencies that we are installing, but I can also add it explicitly if you want. Let me update it

Ah, that makes sense. If that is the case we can leave it as it is. Thank you.

**Comment by carinaya** [comment]
Hi @sandygross after I tried again, I encounter an error again. it states that:
```
| Ran pip subprocess with arguments:
['C:\\Users\\Carina Ya\\miniconda3\\envs\\mathdistops\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\Car]
Pip subprocess output:

Pip subprocess error:
ERROR: Invalid requirement: 'python-math=0.0.1' (from line 1 of C:\Users\Carina Ya\Desktop\condaenv.9y6iw1qv.requiremen)
Hint: = is not a valid operator. Did you mean == ?

failed

CondaEnvException: Pip failed
```


Maybe we could get rid of the math, cuz I think math is already included in the base python. In addtion, scipy and numpy could accomplish most work we need.

**Comment by sivakornchong** [comment]
I have the same error as @carinaya. It is just syntax error: just put == instead. But I also agree that we can remove this line.

**Comment by sandygross** [comment]
Thanks for catching that guys. I will update that in the break!

**Review by carinaya — APPROVED** [review]

**Pull request merged**
